<div id="login_container">
    <div><h1>Welcome to use 'MRFC' to book channel class!</h1></div>
    <div>
        <form method="post" action="">
            <table>
                <tr>
                    <td>username: </td>
                    <td><input type="text" name="username" /></td>
                </tr>
                <tr>
                    <td>password: </td>
                    <td><input type="password" name="password" /></td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                    <input type="submit" value="submit" />
                    </td>
                </tr>


            <table>
        </form>
    </div>
</div>
