<div id="login_container">
    <div><h1>Welcome to use 'MRFC' to book channel class!</h1></div>
    <div>
        <form method="post" action="#" onsubmit="return validate_form(this);">
            <table>
                <tr>
                    <td>username: </td>
                    <td><input type="text" name="username" /></td>
                </tr>
                <tr>
                    <td>password: </td>
                    <td><input type="password" name="password" /></td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                    <input type="submit" value="submit" />
                    </td>
                </tr>


            <table>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?=SITE_ROOT ?>/js/form.js"></script>
<script type="text/javascript">
   function _showmsg(msg) {
        alert(msg);    
   }
   function validate_form(form) {
       var criteria = {username:{empty: '用户名不能为空!'},
                        password:{empty: '密码不能为空!'}}
       var myform = new Form(form, criteria);
       myform.validate();
   }
</script>
